// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {SafeTransferLib} from "@solady/utils/SafeTransferLib.sol";

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";

import {IPoolManager} from "@uniswap/v4-core/src/interfaces/IPoolManager.sol";
import {Hooks, IHooks} from "@uniswap/v4-core/src/libraries/Hooks.sol";
import {SafeCast} from "@uniswap/v4-core/src/libraries/SafeCast.sol";
import {StateLibrary} from "@uniswap/v4-core/src/libraries/StateLibrary.sol";
import {BalanceDelta} from "@uniswap/v4-core/src/types/BalanceDelta.sol";
import {
    BeforeSwapDelta,
    BeforeSwapDeltaLibrary,
    toBeforeSwapDelta
} from "@uniswap/v4-core/src/types/BeforeSwapDelta.sol";
import {Currency} from "@uniswap/v4-core/src/types/Currency.sol";
import {PoolId, PoolIdLibrary} from "@uniswap/v4-core/src/types/PoolId.sol";
import {PoolKey} from "@uniswap/v4-core/src/types/PoolKey.sol";

import {BaseHook} from "v4-hooks-public/lib/v4-periphery/src/utils/BaseHook.sol";

import {CurrencySettler} from "@gemfot/libraries/CurrencySettler.sol";
import {MemecoinFinder} from "@gemfot/types/MemecoinFinder.sol";

import {Notifier} from "@gemfot/hooks/Notifier.sol";
import {StoreKeys} from "@gemfot/types/StoreKeys.sol";

import {IInitialPrice} from "@gemfot-interfaces/IInitialPrice.sol";
import {ILaunch} from "@gemfot-interfaces/ILaunch.sol";
import {IMemecoin} from "@gemfot-interfaces/IMemecoin.sol";

/**
 * The PositionManager is a Uniswap V4 hook that controls the user journey from token creation,
 * to fair launch, to ongoing swaps.
 *
 * The creator of the pool will receive an ERC721 representation of the token. The holder of
 * this token will be the recipient of any creator fees generated by the token in the pool.
 *
 * Hook interactions have aimed to be abstracted into inherited contracts to simplify both
 * functionality and readability. Specific use of each of these contracts has been denoted
 * within comments using square brackets where possible.
 */

contract GemFotManager is BaseHook, FeeDistributor, InternalSwapPool, StoreKeys {
    /**
     * Parameters required when launching a new token.
     *
     * @member name Name of the token
     * @member symbol Symbol of the token
     * @member tokenUri The generated ERC721 token URI
     * @member initialTokenFairLaunch The amount of tokens to add as single sided fair launch liquidity
     * @member fairLaunchDuration The duration of the fair launch period
     * @member premineAmount The amount of tokens that the creator will buy themselves
     * @member creator The address that will receive the ERC721 ownership and premined ERC20 tokens
     * @member creatorFeeAllocation The percentage of fees the creators wants to take from the BidWall
     * @member launchAt The timestamp at which the token will launch
     * @member initialPriceParams The encoded parameters for the Initial Price logic
     * @member feeCalculatorParams The encoded parameters for the fee calculator
     */
    struct LaunchParams {
        string name;
        string symbol;
        string tokenUri;
        uint initialTokenFairLaunch;
        uint fairLaunchDuration;
        uint premineAmount;
        address creator;
        uint24 creatorFeeAllocation;
        uint launchAt;
        bytes initialPriceParams;
        bytes feeCalculatorParams;
    }
}
