// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {IFeeCalculator} from "@gemfot-interfaces/IFeeCalculator.sol";
import {IInitialPrice} from "@gemfot-interfaces/IInitialPrice.sol";
import {ILaunch} from "@gemfot-interfaces/ILaunch.sol";
import {IMemecoin} from "@gemfot-interfaces/IMemecoin.sol";
import {BidWall} from "@gemfot/bidwall/BidWall.sol";
import {FairLaunch} from "@gemfot/hooks/FairLaunch.sol";
import {FeeDistributor} from "@gemfot/hooks/FeeDistributor.sol";
import {FeeExemptions} from "@gemfot/hooks/FeeExemptions.sol";
import {InternalSwapPool} from "@gemfot/hooks/InternalSwapPool.sol";
import {Notifier} from "@gemfot/hooks/Notifier.sol";
import {UniswapHookEvents} from "@gemfot/libraries/UniswapHookEvents.sol";
import {TreasuryActionManager} from "@gemfot/treasury/ActionManager.sol";
import {MemecoinTreasury} from "@gemfot/treasury/MemecoinTreasury.sol";
import {MemecoinFinder} from "@gemfot/types/MemecoinFinder.sol";
import {StoreKeys} from "@gemfot/types/StoreKeys.sol";
import {MarketCappedPriceParams} from "@gemfot/types/USDCMarketCappedPrice.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeTransferLib} from "@solady/utils/SafeTransferLib.sol";
import {IPoolManager} from "@uniswap/v4-core/src/interfaces/IPoolManager.sol";
import {Hooks, IHooks} from "@uniswap/v4-core/src/libraries/Hooks.sol";
import {SafeCast} from "@uniswap/v4-core/src/libraries/SafeCast.sol";
import {StateLibrary} from "@uniswap/v4-core/src/libraries/StateLibrary.sol";
import {BalanceDelta} from "@uniswap/v4-core/src/types/BalanceDelta.sol";
import {
    BeforeSwapDelta,
    BeforeSwapDeltaLibrary,
    toBeforeSwapDelta
} from "@uniswap/v4-core/src/types/BeforeSwapDelta.sol";
import {Currency} from "@uniswap/v4-core/src/types/Currency.sol";
import {PoolId, PoolIdLibrary} from "@uniswap/v4-core/src/types/PoolId.sol";
import {PoolKey} from "@uniswap/v4-core/src/types/PoolKey.sol";
import {CurrencySettler} from "@uniswap/v4-core/test/utils/CurrencySettler.sol";
import {BaseHook} from "v4-hooks-public/lib/v4-periphery/src/utils/BaseHook.sol";
import {ModifyLiquidityParams, SwapParams} from "@uniswap/v4-core/src/types/PoolOperation.sol";


/**
 * The GemFotManager is a Uniswap V4 hook that controls the user journey from token creation,
 * to fair launch, to ongoing swaps.
 *
 * The creator of the pool will receive an ERC721 representation of the token. The holder of
 * this token will be the recipient of any creator fees generated by the token in the pool.
 *
 * Hook interactions have aimed to be abstracted into inherited contracts to simplify both
 * functionality and readability. Specific use of each of these contracts has been denoted
 * within comments using square brackets where possible.
 */

contract GemFotManager is BaseHook, FeeDistributor, InternalSwapPool, StoreKeys {
    using BeforeSwapDeltaLibrary for BeforeSwapDelta;
    using CurrencySettler for Currency;
    using PoolIdLibrary for PoolKey;
    using SafeCast for uint;
    using StateLibrary for IPoolManager;
    using MemecoinFinder for PoolKey;
    using SafeTransferLib for address;

    error CallerIsNotBidWall();
    error CannotBeInitializedDirectly();
    error InsufficientLaunchFee(uint _paid, uint _required);
    error TokenNotLaunched(uint _launchesAt);
    error UnknownPool(PoolId _poolId);


    /// Emitted when a Launch pool is created
    event PoolCreated(
        PoolId indexed _poolId,
        address _memecoin,
        address _memecoinTreasury,
        uint _tokenId,
        bool _currencyFlipped,
        uint _launchFee,
        LaunchParams _params
    );

    /// Emitted when a Launch pool is scheduled
    event PoolScheduled(PoolId indexed _poolId, uint _launchesAt);

    /// Emitted when a pool swap occurs
    event PoolSwap(
        PoolId indexed poolId,
        int flAmount0,
        int flAmount1,
        int flFee0,
        int flFee1,
        int ispAmount0,
        int ispAmount1,
        int ispFee0,
        int ispFee1,
        int uniAmount0,
        int uniAmount1,
        int uniFee0,
        int uniFee1
    );

    /// Emitted after any transaction to share pool state
    event PoolStateUpdated(
        PoolId indexed _poolId,
        uint160 _sqrtPriceX96,
        int24 _tick,
        uint24 _protocolFee,
        uint24 _swapFee,
        uint128 _liquidity
    );

    /// Emitted when a user successfully premines their token
    event PoolPremine(PoolId indexed _poolId, int _premineAmount);

    /// Emitted when unused premine is forfeited (deadline / sold out) and tstore cleared
    event PremineBurned(PoolId indexed _poolId, uint _premineAmount);

    /// Emitted when the `IInitialPrice` contract has been updated
    event InitialPriceUpdated(address _initialPrice);

    /// Emitted when the `FairLaunch` contract has burned unsold fair launch supply
    event FairLaunchBurn(PoolId indexed _poolId, uint _unsoldSupply);

    /**
     * Defines our constructor parameters.
     *
     * @custom:member nativeToken The native ETH equivalent token used by protocol
     * @custom:member poolManager The Uniswap V4 {PoolManager} contract
     * @custom:member feeDistribution The default fee distribution configuration
     * @custom:member initialPrice Set initial price calculator address
     * @custom:member protocolOwner The EOA that will be the initial owner
     * @custom:member protocolFeeRecipient The recipient EOA of all
     * @custom:member feeEscrow The {FeeEscrow} contract to be used by the PositionManager
     * @custom:member feeExemptions The default global FeeExemption values
     * @custom:member actionManager The {TreasuryActionManager} contract
     * @custom:member bidWall The {BidWall} contract to be used by the PositionManager
     * @custom:member fairLaunch The {FairLaunch} contract to be used by the PositionManager
     */
    struct ConstructorParams {
        address nativeToken;
        IPoolManager poolManager;
        FeeDistribution feeDistribution;
        IInitialPrice initialPrice;
        address protocolOwner;
        address protocolFeeRecipient;
        address feeEscrow;
        FeeExemptions feeExemptions;
        TreasuryActionManager actionManager;
        BidWall bidWall;
        FairLaunch fairLaunch;
    }

    /**
     * Parameters required when launching a new token.
     *
     * @custom:member name Name of the token
     * @custom:member symbol Symbol of the token
     * @custom:member tokenUri The generated ERC721 token URI
     * @custom:member initialTokenFairLaunch The amount of tokens to add as single sided fair launch liquidity
     * @custom:member fairLaunchDuration The duration of the fair launch period (in seconds - YEAH YEAH)
     * @custom:member premineAmount The amount of tokens that the creator will buy themselves
     * @custom:member creator The address that will receive the ERC721 ownership and premined ERC20 tokens
     * @custom:member creatorFeeAllocation The percentage of fees the creators wants to take from the BidWall
     * @custom:member launchAt The timestamp at which the token will launch
     * @custom:member initialPriceParams The encoded parameters for the Initial Price logic
     * @custom:member feeCalculatorParams The encoded parameters for the fee calculator
     */
    struct LaunchParams {
        string name;
        string symbol;
        string tokenUri;
        uint initialTokenFairLaunch;
        uint fairLaunchDuration;
        uint premineAmount;
        address creator;
        uint24 creatorFeeAllocation;
        uint launchAt;
        bytes initialPriceParams;
        bytes feeCalculatorParams;
    }

    /// The minimum amount before a distribution is triggered
    uint public constant MIN_DISTRIBUTE_THRESHOLD = 100 * 10 ** 6; // USDC

    /// The `dEaD` address to burn our unsold memecoins to
    address public constant BURN_ADDRESS = 0x000000000000000000000000000000000000dEaD;

    /// The contract that will be used for launching tokens
    ILaunch public launchContract;

    /// Our starting token sqrtPriceX96
    IInitialPrice public initialPrice;

    /// Internal storage to allow the `beforeSwap` tick value to be used in `afterSwap`
    int24 internal _beforeSwapTick;

    /// Store the address that will collect protocol fees
    address internal protocolFeeRecipient;

    /// Store the contract that will manage our Bidwall interactions
    BidWall public bidWall;

    /// The contract that handles the FairLaunch flow
    FairLaunch public fairLaunch;


    /// The contract that handles the token Treasury actions
    TreasuryActionManager public actionManager;

    /// Store the contract that will manage fee exemptions
    FeeExemptions public feeExemptions;

    /// Store our {Notifier} contract
    Notifier public notifier;

    /// Store the block timestamp when a poolId is set to launch
    mapping(PoolId _poolId => uint _launchTime) public launchesAt;

    /**
     * Initializes our {BaseHook} contract and initializes all implemented hooks.
     */
    constructor(
        ConstructorParams memory params
    )
        BaseHook(params.poolManager)
        FeeDistributor(params.nativeToken, params.feeDistribution, params.protocolOwner, params.feeEscrow)
    {
        // Set our contract references
        initialPrice = params.initialPrice;

        // Set our protocol fee recipient
        protocolFeeRecipient = params.protocolFeeRecipient;

        // Register our FeeExemption contract
        feeExemptions = params.feeExemptions;

        // Register our BidWall contract
        bidWall = params.bidWall;

        // Register our FairLaunch logic
        fairLaunch = params.fairLaunch;

        // Register our ActionManager
        actionManager = params.actionManager;

        // Deploy our notifier
        notifier = new Notifier(params.protocolOwner);

        // Approve the BidWall to manage native token from the PositionManager
        IERC20(params.nativeToken).approve(address(bidWall), type(uint).max);
        IERC20(params.nativeToken).approve(address(fairLaunch), type(uint).max);
    }

    /**
     * Creates a new ERC20 memecoin token creating and an ERC721 that signifies ownership of the
     * launched collection. The token is then initialized into a UV4 pool.
     *
     * The FairLaunch period will start in this call, as soon as the pool is initialized.
     *
     * @return memecoin_ The created ERC20 token address
     */
    function launch(
        LaunchParams calldata _params
    ) external payable returns (address memecoin_) {
        (MarketCappedPriceParams memory params) = abi.decode(_params.initialPriceParams, (MarketCappedPriceParams));

        uint tokenId;
        address payable memecoinTreasury;

        // Launch our token
        (memecoin_, memecoinTreasury, tokenId) = launchContract.launch(_params);

        // Check if our pool currency is flipped
        bool currencyFlipped = nativeToken >= memecoin_;

        // Create our Uniswap pool and store the pool key for lookups
        PoolKey memory _poolKey = PoolKey({
            currency0: Currency.wrap(!currencyFlipped ? nativeToken : memecoin_),
            currency1: Currency.wrap(currencyFlipped ? nativeToken : memecoin_),
            fee: 0,
            tickSpacing: 60,
            hooks: IHooks(address(this))
        });

        // Initialize the {MemecoinTreasury} with `PoolKey`
        MemecoinTreasury(memecoinTreasury)
            .initialize(payable(address(this)), address(actionManager), nativeToken, _poolKey);

        // Set the PoolKey to storage
        _poolKeys[memecoin_] = _poolKey;
        PoolId poolId = _poolKey.toId();

        // If we have a non-zero creator fee allocation, then we need to update our creator's
        // fee allocation.
        if (_params.creatorFeeAllocation != 0) {
            creatorFee[poolId] = _params.creatorFeeAllocation;
        }

        // Initialize all fee calculators attached to the pool, along with any custom parameters
        _initializeFeeCalculators(poolId, _params.feeCalculatorParams);

        // Initialize our memecoin with the sqrtPriceX96
        int24 initialTick = poolManager.initialize(
            _poolKey, initialPrice.getSqrtPriceX96(msg.sender, currencyFlipped, _params.initialPriceParams)
        );

        // Check if we have an initial launching fee, check that enough ETH has been sent
        uint launchFee = getLaunchingFee(_params.initialPriceParams);

        emit PoolCreated({
            _poolId: poolId,
            _memecoin: memecoin_,
            _memecoinTreasury: memecoinTreasury,
            _tokenId: tokenId,
            _currencyFlipped: currencyFlipped,
            _launchFee: launchFee,
            _params: _params
        });

        /**
         * [PREMINE] If the creator has requested tokens from their initial fair launch
         * allocation, which they can purchase in the same transaction.
         */

        if (_params.premineAmount != 0) {
            int premineAmount = _params.premineAmount.toInt256();
            assembly { tstore(poolId, premineAmount) }
        }

        /**
         * [FL] At token creation, x% of token supply is put into a one-sided position.
         */

        // We don't currently require any token approval to create a fair launch position, but
        // when the position closes, the {FairLaunch} contract will supply the {PoolManager}
        // with tokens from this contract.
        IMemecoin(memecoin_).approve(address(fairLaunch), type(uint).max);

        // Regardless of having a fair launch, we need to call `createPosition` as this
        // instantiates our storage struct that is required for when the position is closed
        // and the tokens are moved to a Uniswap V4 liquidity position.
        fairLaunch.createPosition({
            _poolId: poolId,
            _initialTick: initialTick,
            _launchesAt: _params.launchAt > block.timestamp ? _params.launchAt : block.timestamp,
            _initialTokenFairLaunch: _params.initialTokenFairLaunch,
            _tokenTotalSupply: params.totalSupply,
            _fairLaunchDuration: _params.fairLaunchDuration
        });

        /**
         * [SCHEDULE] If we have a timestamp in the future, then we set our schedule mapping.
         */

        if (_params.launchAt > block.timestamp) {
            launchesAt[poolId] = _params.launchAt;
            emit PoolScheduled(poolId, _params.launchAt);
        } else {
            // If the `launchAt` timestamp has already passed, then use the current timestamp
            launchesAt[poolId] = block.timestamp;
        }

        // rewrite since we are taking USDC instead of ETH
        if (launchFee != 0) {
            uint allowance = IERC20(nativeToken).allowance(msg.sender, address(this));
            if (allowance < launchFee) {
                revert InsufficientLaunchFee(allowance, launchFee);
            }

            // Pay the launching fee to our fee recipient
            nativeToken.safeTransferFrom(msg.sender, protocolFeeRecipient, launchFee);
        }

        // After our contract is initialized, we mark our pool as initialized and emit
        // our state update to notify the UX of current prices, etc. This will include
        // optional liquidity modifications from the Fair Launch logic.
        _emitPoolStateUpdate(poolId, IHooks.afterInitialize.selector, abi.encode(tokenId, _params));
    }

    /**
     * Returns the PoolKey mapped to the token address. If none is set then a zero value
     * will be returned for the fields.
     *
     * @dev The easiest way to check for an empty response is `tickSpacing = 0`
     *
     * @param _token The address of the ERC20 token
     *
     * @return The corresponding {PoolKey} for the token
     */
    function poolKey(
        address _token
    ) external view returns (PoolKey memory) {
        return _poolKeys[_token];
    }

    /**
     * Gets the USDC fee that must be paid to launch a token.
     *
     * @return The USDC value of the fee
     */
    function getLaunchingFee(
        bytes calldata _initialPriceParams
    ) public view returns (uint) {
        return initialPrice.getLaunchingFee(msg.sender, _initialPriceParams);
    }


    /**
     * Defines the Uniswap V4 hooks that are used by our implementation. This will determine
     * the address that our contract **must** be deployed to for Uniswap V4. This address suffix
     * is shown in the dev comments for this function call.
     *
     * @dev 1011 1111 0111 00 == 2FDC
     */
    function getHookPermissions() public pure override returns (Hooks.Permissions memory) {
        return Hooks.Permissions({
            beforeInitialize: true, // Prevent initialize
            afterInitialize: false,
            beforeAddLiquidity: true, // [FairLaunch], [InternalSwapPool]
            afterAddLiquidity: true, // [EventTracking]
            beforeRemoveLiquidity: true, // FairLaunch], [InternalSwapPool]
            afterRemoveLiquidity: true, // [EventTracking]
            beforeSwap: true, // FairLaunch], [InternalSwapPool]
            afterSwap: true, // [FeeDistributor], [InternalSwapPool], [BidWall], [EventTracking]
            beforeDonate: false,
            afterDonate: true, // [EventTracking]
            beforeSwapReturnDelta: true, // [InternalSwapPool]
            afterSwapReturnDelta: true, // [FeeDistributor]
            afterAddLiquidityReturnDelta: false,
            afterRemoveLiquidityReturnDelta: false
        });
    }

    /**
     * The hook called before the state of a pool is initialized. Prevents external contracts
     * from initializing pools using our contract as a hook.
     *
     * @dev As we call `poolManager.initialize` from the IHooks contract itself, we bypass this
     * hook call as therefore bypass the prevention.
     */
    function _beforeInitialize(
        address,
        PoolKey calldata,
        uint160
    ) internal override onlyPoolManager returns (bytes4) {
        revert CannotBeInitializedDirectly();
    }


    /**
     * [ISP] Fills first from fee-token inventory, then reduces the remaining swap amount.
     * [FL] Fills any remaining amount from FairLaunch (and closes when supply hits zero / window ends).
     * [FD] Captures fees from both ISP and FairLaunch fills.
     *
     * @param _sender The address calling the swap
     * @param _key The key for the pool
     * @param _params The parameters for the swap
     * @param _hookData Arbitrary data handed into the PoolManager by the swapper to be be passed on to the hook
     *
     * @return selector_ The function selector for the hook
     * @return beforeSwapDelta_ The hook's delta in specified and unspecified currencies. Positive: the hook is owed/took currency, negative: the hook owes/sent currency
     * @return swapFee_ The percentage fee applied to our swap
     */

    //  function _beforeSwap(address sender, PoolKey calldata key, SwapParams calldata params, bytes calldata hookData) internal override returns (bytes4 selector_, BeforeSwapDelta beforeSwapDelta_, uint24 swapFee_)

    function _beforeSwap(
        address _sender,
        PoolKey calldata _key,
        SwapParams calldata _params,
        bytes calldata _hookData
    ) internal override returns (
        bytes4 selector_,
        BeforeSwapDelta beforeSwapDelta_,
        uint24
    ) {
        /**
         * [SCHEDULE][PREMINE] Creators pass their address in hookData (`abi.encode(user)`).
         * Premine amount is set at launch via tstore (line ~320) and is already included in
         * FairLaunch supply — no addSupply. On success or expiry, clear tstore.
         */
        PoolId poolId = _key.toId();
        bool nativeIsZero = nativeToken == Currency.unwrap(_key.currency0);
        address swapper = _resolveSwapper(_sender, _hookData);
        int premineAmount = _tload(PoolId.unwrap(poolId));
        bool isCreatorPremine;

        if (premineAmount != 0) {
            // Exact-output buy of the reserved premine by the token creator
            isCreatorPremine = swapper == _key.memecoin(nativeToken).creator()
                && _params.amountSpecified == premineAmount
                && nativeIsZero == _params.zeroForOne;

            if (isCreatorPremine) {
                emit PoolPremine(poolId, premineAmount);
                // Clear premine claim so it cannot be reused
                assembly {
                    tstore(poolId, 0)
                }
            }
        }

        {
            uint _launchesAt = launchesAt[poolId];
            if (_launchesAt != 0) {
                if (!isCreatorPremine) {
                    // If the timestamp has not yet passed, then we revert
                    if (_launchesAt > block.timestamp) {
                        revert TokenNotLaunched(_launchesAt);
                    }

                    // Remove the schedule timestamp to prevent future checks
                    delete launchesAt[poolId];
                }
            }
        }

        // Remaining amount for FairLaunch / Uniswap after ISP fills first
        int amountRemaining = _params.amountSpecified;

        // Check if our fair launch period hasn't ended and already been processed
        FairLaunch.FairLaunchInfo memory fairLaunchInfo = fairLaunch.fairLaunchInfo(poolId);
        bool inActiveFairLaunch;

        if (!fairLaunchInfo.closed) {
            /**
             * [FL] If it's not premine, and the FairLaunch window has ended, but our position is still open, then we
             * need to close the position. Clear and forfeit any unused creator premine (burned with unsold supply).
             */
            if (!isCreatorPremine && !fairLaunch.inFairLaunchWindow(poolId)) {
                // Creator missed their premine — clear tstore; tokens are burned with unsold FL supply below
                _clearUnusedPremine(poolId);

                uint unsoldSupply = fairLaunchInfo.supply;

                // closes the fair launch position, putting remaining memecoin supply into the liquidity pool
                // minus the unsold fair launch supply, which is burned
                fairLaunch.closePosition({
                    _poolKey: _key,
                    _tokenFees: _poolFees[poolId].amount1,
                    _nativeIsZero: nativeIsZero
                });

                // burn the unsold fair launch supply (includes any unused premine)
                if (unsoldSupply != 0) {
                    (nativeIsZero ? _key.currency1 : _key.currency0).transfer(BURN_ADDRESS, unsoldSupply);
                    emit FairLaunchBurn(poolId, unsoldSupply);
                }
            } else {
                /**
                 * [FL] If we are still in the FairLaunch window, then we need to prevent any swaps that
                 * are specified to sell the {Memecoin}.
                 */
                if (nativeIsZero != _params.zeroForOne) {
                    revert FairLaunch.CannotSellTokenDuringFairLaunch();
                }

                inActiveFairLaunch = true;
            }
        }

        /**
         * [ISP] Fill first from fee-token inventory (e.g. -100 USDC with 10 USDC of fees → take 10 here).
         * Remaining amount is then passed to FairLaunch / Uniswap.
         */
        (uint tokenIn, uint tokenOut) = _internalSwap(poolManager, _key, _params, nativeIsZero);
        if (tokenIn + tokenOut != 0) {
            // Update our hook delta to reduce the upcoming swap amount to show that we have
            // already spent some of the ETH and received some of the underlying ERC20.
            BeforeSwapDelta internalBeforeSwapDelta = _params.amountSpecified >= 0
                ? toBeforeSwapDelta(-tokenOut.toInt128(), tokenIn.toInt128())
                : toBeforeSwapDelta(tokenIn.toInt128(), -tokenOut.toInt128());

            /**
             * [FD] We need to determine the amount of fees generated by our internal swap to capture,
             * rather than sending the full amount to the end user.
             */
            uint swapFee = _captureAndDepositFees(
                _key, _params, _sender, internalBeforeSwapDelta.getUnspecifiedDelta(), _hookData
            );

            // Increment our swap
            _captureDelta(_params, TS_ISP_AMOUNT0, TS_ISP_AMOUNT1, internalBeforeSwapDelta);
            _captureDeltaSwapFee(_params, TS_ISP_FEE0, TS_ISP_FEE1, swapFee);

            beforeSwapDelta_ = toBeforeSwapDelta(
                beforeSwapDelta_.getSpecifiedDelta() + internalBeforeSwapDelta.getSpecifiedDelta(),
                beforeSwapDelta_.getUnspecifiedDelta() + internalBeforeSwapDelta.getUnspecifiedDelta()
                    + swapFee.toInt128()
            );

            // exact input (-100): remaining = -100 + 10 = -90
            // exact output (+tokens): remaining = wanted - tokenOut
            amountRemaining = _params.amountSpecified >= 0
                ? amountRemaining - int(tokenOut)
                : amountRemaining + int(tokenIn);
        }

        /**
         * [FL] Fill any remaining amount from the FairLaunch position after ISP.
         * Creator premine is sold here from existing FairLaunch supply.
         */
        if (inActiveFairLaunch && amountRemaining != 0) {
            BalanceDelta fairLaunchFillDelta;
            BeforeSwapDelta fairLaunchBeforeSwapDelta;
            (fairLaunchBeforeSwapDelta, fairLaunchFillDelta, fairLaunchInfo) =
                fairLaunch.fillFromPosition(_key, amountRemaining, nativeIsZero);

            // Give the tokens to Uniswap V4 so that it can play good-cop and give them to the user
            _settleDelta(_key, fairLaunchFillDelta);

            /**
             * [FD] We need to determine the amount of fees generated by our fair launch swap to
             * capture, rather than sending the full amount to the end user.
             */
            uint swapFee = _captureAndDepositFees(
                _key, _params, _sender, fairLaunchBeforeSwapDelta.getUnspecifiedDelta(), _hookData
            );

            // Increment our swap
            _captureDelta(_params, TS_FL_AMOUNT0, TS_FL_AMOUNT1, fairLaunchBeforeSwapDelta);
            _captureDeltaSwapFee(_params, TS_FL_FEE0, TS_FL_FEE1, swapFee);

            // Combine ISP + FairLaunch deltas
            beforeSwapDelta_ = toBeforeSwapDelta(
                beforeSwapDelta_.getSpecifiedDelta() + fairLaunchBeforeSwapDelta.getSpecifiedDelta(),
                beforeSwapDelta_.getUnspecifiedDelta() + fairLaunchBeforeSwapDelta.getUnspecifiedDelta()
                    + swapFee.toInt128()
            );

            // A FairLaunch transaction will always facilitate purchasing Memecoin with
            // Native Token. This means that if the `amountSpecified` not negative, then we will
            // have captured the fee in Native Token and as such we need to reduce the amount of
            // revenue that we record.
            if (amountRemaining >= 0 && swapFee != 0) {
                fairLaunch.modifyRevenue(poolId, -swapFee.toInt128());
            }

            // If we have run out of tokens, then we can close the pool
            if (fairLaunchInfo.supply == 0) {
                // Sold out before creator bought — forfeit premine claim and clear tstore
                _clearUnusedPremine(poolId);

                fairLaunch.closePosition({
                    _poolKey: _key,
                    _tokenFees: _poolFees[poolId].amount1,
                    _nativeIsZero: nativeIsZero
                });
            }
        }

        // Capture the beforeSwap tick value before actioning our Uniswap swap
        (, _beforeSwapTick,,) = poolManager.getSlot0(_key.toId());

        // Check if the BidWall has become stale, and allow liquidity to be extracted before a
        // threshold has been built.
        bidWall.checkStalePosition({
            _poolKey: _key,
            _currentTick: _beforeSwapTick,
            _nativeIsZero: nativeIsZero
        });

        // Set our return selector
        selector_ = IHooks.beforeSwap.selector;
    }

    /**
     * [FD] Captures fees from the swap to either distribute or send to ISP
     * [ISP] Once a swap has been made, we distribute fees to our LPs and emit our price update event.
     * [FD] Tracks the swap for future fee calculations
     * [FL][BW] If Fair Launch ended then we may have an ETH to deposit into the BidWall
     *
     * @param _sender The sender (or swap contract) making the call
     * @param _key The key for the pool
     * @param _params The parameters for the swap
     * @param _delta The amount owed to the caller (positive) or owed to the pool (negative)
     * @param _hookData Arbitrary data handed into the PoolManager by the swapper to be be passed on to the hook
     *
     * @return selector_ The function selector for the hook
     * @return hookDeltaUnspecified_ The hook's delta in unspecified currency. Positive: the hook is owed/took currency, negative: the hook owes/sent currency
     */

    //  function _afterSwap(address sender, PoolKey calldata key, SwapParams calldata params, BalanceDelta delta, bytes calldata hookData) internal override returns (bytes4 selector_, int128 hookDeltaUnspecified_) 

    function _afterSwap(
        address _sender,
        PoolKey calldata _key,
        SwapParams calldata _params,
        BalanceDelta _delta,
        bytes calldata _hookData
    ) internal override returns (
        bytes4 selector_,
        int128 hookDeltaUnspecified_
    ) {
        /**
         * [FD] We need to determine the amount of fees generated by our Uniswap swap to capture,
         * rather than sending the full amount to the end user.
         */

        // Determine the currency that we will be taking our fee from
        (int128 amount0, int128 amount1) = (_delta.amount0(), _delta.amount1());
        int128 swapAmount = _params.amountSpecified < 0 == _params.zeroForOne ? amount1 : amount0;

        // Capture the swap fees and dispatch the referrer's share if set
        uint swapFee = _captureAndDepositFees(_key, _params, _sender, swapAmount, _hookData);

        // Increment our swap
        assembly {
            tstore(TS_UNI_AMOUNT0, amount0)
            tstore(TS_UNI_AMOUNT1, amount1)
        }

        _captureDeltaSwapFee(_params, TS_UNI_FEE0, TS_UNI_FEE1, swapFee);

        /**
         * [ISP] Distribute any fees that have been converted by the swap.
         */

        _distributeFees(_key);

        /**
         * [FD] If we have a feeCalculator, then we want to track the swap data for any
         * dynamic calculations.
         */

        PoolId poolId = _key.toId();

        {
            IFeeCalculator _feeCalculator = getFeeCalculator(fairLaunch.inFairLaunchWindow(poolId));
            if (address(_feeCalculator) != address(0)) {
                _feeCalculator.trackSwap(_sender, _key, _params, _delta, _hookData);
            }
        }

        // Set our return selector
        hookDeltaUnspecified_ = swapFee.toInt128();

        selector_ = IHooks.afterSwap.selector;

        // Emit our compiled swap data
        _emitSwapUpdate(poolId, _sender);

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(poolId, selector_, abi.encode(_sender, _params, _delta));
    }


    /**
     * Updates the `IInitialPrice` contract address that is used during `launch` to calculate
     * the initial tick / sqrtPriceX96 value.
     *
     * @param _initialPrice The contract address for the `IInitialPrice` contract
     */
    function setInitialPrice(
        address _initialPrice
    ) public onlyOwner {
        initialPrice = IInitialPrice(_initialPrice);
        emit InitialPriceUpdated(_initialPrice);
    }



    /**
     * We want to be able to distribute fees across our {FeeDistribution} recipients
     * when we reach a set threshold. This will only ever distribute the ETH equivalent
     * token, as the non-ETH token will be converted via the {InternalSwapPool} hook logic.
     *
     * @dev There referrer has already received their share, so they do not need to be
     * taken into account at this point.
     *
     * @param _poolKey The PoolKey reference that will have fees distributed
     */
    function _distributeFees(PoolKey memory _poolKey) internal {
        PoolId poolId = _poolKey.toId();

        // Get the amount of the native token available to distribute
        uint distributeAmount = _poolFees[poolId].amount0;

        // Ensure that the collection has sufficient fees available
        if (distributeAmount < MIN_DISTRIBUTE_THRESHOLD) return;

        // Reduce our available fees for the pool
        _poolFees[poolId].amount0 = 0;

        // Find the distribution amount across our different users. The amount that treasury
        // receives will be determined by variables throughout the distribution flow, such as
        // the BidWall being disabled, etc.
        (uint bidWallFee, uint creatorFee, uint protocolFee) = feeSplit(poolId, distributeAmount);
        uint treasuryFee;

        // Load our memecoin so that we can query the creator and treasury
        IMemecoin memecoin = _poolKey.memecoin(nativeToken);

        // Check if our creator has been burned, as this changes fee allocation in a number of places
        address poolCreator = memecoin.creator();
        bool poolCreatorBurned = poolCreator == address(0);

        if (creatorFee != 0) {
            // Ensure that the pool creator has not burned their ownership and send them the fees
            if (!poolCreatorBurned) {
                _allocateFees(poolId, poolCreator, creatorFee);
            }
            // If the pool creator has burned their ownership, then we instead send fees directly
            // to the BidWall.
            else {
                bidWallFee += creatorFee;
                creatorFee = 0;
            }
        }

        if (bidWallFee != 0) {
            // Check if we have an active BidWall for the pool. If we don't have an active BidWall, then
            // we will need to instead allocate this to the protocol. If we are still in the FairLaunch
            // window the this will just carry over into the FairLaunch created position, so we already
            // have this value attributed.
            if (bidWall.isBidWallEnabled(poolId) && !fairLaunch.inFairLaunchWindow(poolId)) {
                // Otherwise, we can deposit directly into the BidWall as we have permission to modify
                // liquidity outside of the window.
                bidWall.deposit(_poolKey, bidWallFee, _beforeSwapTick, nativeToken == Currency.unwrap(_poolKey.currency0));
            } else {
                // If we cannot import into BidWall, then treasury will be allocated the fees
                treasuryFee += bidWallFee;
                bidWallFee = 0;
            }
        }

        if (treasuryFee != 0) {
            // Ensure that the pool creator has not burned their ownership and send treasury the fees
            if (!poolCreatorBurned) {
                _allocateFees(poolId, memecoin.treasury(), treasuryFee);
            } else {
                // If we cannot allocate to treasury, then protocol receives the fees
                protocolFee += treasuryFee;
                treasuryFee = 0;
            }
        }

        // Finally we allocate our protocol fees
        if (protocolFee != 0) {
            _allocateFees(poolId, protocolFeeRecipient, protocolFee);
        }

        emit PoolFeesDistributed(poolId, distributeAmount, creatorFee, bidWallFee, treasuryFee, protocolFee);
    }



    /**
     * Using the `tstore` values that we have generated along the way, we emit an event that shows
     * the breakdown of fees earned at each swap point.
     *
     * @param _poolId The PoolId that is being emitted
     * @param _sender The router of the swap
     */
    function _emitSwapUpdate(PoolId _poolId, address _sender) internal {
        // Emit our protocol-recognised event
        emit PoolSwap(
            _poolId,
            _tload(TS_FL_AMOUNT0), _tload(TS_FL_AMOUNT1), _tload(TS_FL_FEE0), _tload(TS_FL_FEE1),
            _tload(TS_ISP_AMOUNT0), _tload(TS_ISP_AMOUNT1), _tload(TS_ISP_FEE0), _tload(TS_ISP_FEE1),
            _tload(TS_UNI_AMOUNT0), _tload(TS_UNI_AMOUNT1), _tload(TS_UNI_FEE0), _tload(TS_UNI_FEE1)
        );

        // Emit the Uniswap V4 standardised event
        UniswapHookEvents.emitHookSwapEvent({
            _poolId: _poolId,
            _sender: _sender,
            _amount0: _tload(TS_FL_AMOUNT0) + _tload(TS_ISP_AMOUNT0),
            _amount1: _tload(TS_FL_AMOUNT1) + _tload(TS_ISP_AMOUNT1),
            _fee0: _tload(TS_FL_FEE0) + _tload(TS_ISP_FEE0),
            _fee1: _tload(TS_FL_FEE1) + _tload(TS_ISP_FEE1)
        });

        // @dev We flush the tstore values at this point as although they are only set
        // explicitly and not modified, both the FL and ISP could be bypassed but the tstore
        // data would remain.

        assembly {
            tstore(TS_FL_AMOUNT0, 0)
            tstore(TS_FL_AMOUNT1, 0)
            tstore(TS_FL_FEE0, 0)
            tstore(TS_FL_FEE1, 0)
            tstore(TS_ISP_AMOUNT0, 0)
            tstore(TS_ISP_AMOUNT1, 0)
            tstore(TS_ISP_FEE0, 0)
            tstore(TS_ISP_FEE1, 0)
            tstore(TS_UNI_AMOUNT0, 0)
            tstore(TS_UNI_AMOUNT1, 0)
            tstore(TS_UNI_FEE0, 0)
            tstore(TS_UNI_FEE1, 0)
        }
    }

    /**
     * Emits an event that provides pool state updates and passes the data to subscribers.
     *
     * @param _poolId The PoolId that has been updated
     * @param _key The selector being sent to notification subscribers
     * @param _data The data being sent to notification subscribers
     */
     function _emitPoolStateUpdate(PoolId _poolId, bytes4 _key, bytes memory _data) internal {
        // Notify our subscribed contracts
        notifier.notifySubscribers(_poolId, _key, _data);

        // Emit our event
        (uint160 sqrtPriceX96, int24 tick, uint24 protocolFee, uint24 swapFee) = poolManager.getSlot0(_poolId);
        emit PoolStateUpdated(_poolId, sqrtPriceX96, tick, protocolFee, swapFee, poolManager.getLiquidity(_poolId));
    }

    /**
     * Allows the contract used to launch a new token to be updated.
     *
     * @param _launchContract The new {ILaunch} contract address
     */
    function setLaunch(
        address _launchContract
    ) public onlyOwner {
        launchContract = ILaunch(_launchContract);
    }

    /**
     * Calls for the BidWall to be closed, as this requires callback from the {PoolManager}.
     */
    function closeBidWall(
        PoolKey memory _key
    ) public {
        // Ensure that the call is made by the BidWall which validates logic
        if (msg.sender != address(bidWall)) {
            revert CallerIsNotBidWall();
        }

        // Ensure that the PoolKey that is being closed is valid and recognised on the protocol,
        // otherwise we could processing issues and false positives in upcoming steps. We need to
        // ensure that the PoolKey is recognised (by checking the hooks address is not zero) and
        // that the PoolId matches when encoded.
        PoolKey memory storedKey = _poolKeys[address(_key.memecoin(nativeToken))];
        if (storedKey.hooks == IHooks(address(0)) || PoolId.unwrap(storedKey.toId()) != PoolId.unwrap(_key.toId())) {
            revert UnknownPool(_key.toId());
        }

        // Action our BidWall closure via the {PoolManager} unlock
        poolManager.unlock(abi.encode(_key));
    }


    /**
     * Capture the fees from our swap. This could either be from an internal swap (`beforeSwap`)
     * or from the actual Uniswap swap (`afterSwap`).
     *
     * @dev This is only used due to too many variables in the `beforeSwap` function
     *
     * @param _key The {PoolKey} that the swap was made against
     * @param _params The swap parameters called in the swap
     * @param _sender The sender of the swap call
     * @param _delta The balance change from the swap
     * @param _hookData Additional bytes data passed in the swap
     *
     * @return swapFee_ The fee taken from the swap
     */
    function _captureAndDepositFees(
        PoolKey calldata _key,
        SwapParams memory _params,
        address _sender,
        int128 _delta,
        bytes calldata _hookData
    ) internal returns (uint swapFee_) {
        // Determine the swap fee currency based on swap parameters
        Currency swapFeeCurrency = _params.amountSpecified < 0 == _params.zeroForOne ? _key.currency1 : _key.currency0;

        // Capture our swap fees amount
        swapFee_ = _captureSwapFees({
            _poolManager: poolManager,
            _key: _key,
            _params: _params,
            _feeCalculator: getFeeCalculator(fairLaunch.inFairLaunchWindow(_key.toId())),
            _swapFeeCurrency: swapFeeCurrency,
            _swapAmount: uint128(_delta < 0 ? -_delta : _delta),
            _feeExemption: feeExemptions.feeExemption(_sender)
        });

        // If we have no swap fees, then we have nothing to process
        if (swapFee_ == 0) {
            return swapFee_;
        }

        // Deposit the remaining fees against our pool to be either distributed to
        // others, or placed into the Internal Swap Pool to be converted into an ETH
        // equivalent token. We don't reduce the amount by referrer fees as we still
        // need to claim this from the PoolManager.
        _depositFees(
            _key,
            Currency.unwrap(swapFeeCurrency) == nativeToken ? swapFee_ : 0,
            Currency.unwrap(swapFeeCurrency) == nativeToken ? 0 : swapFee_
        );
    }

    /**
     * We need to be able to set the (un)specified token to amount0 / amount1 for the expected
     * event emit format.
     *
     * @param _params The `SwapParams` used to capture the delta
     * @param _key_amount0 The tstore key for the token0 amount
     * @param _key_amount1 The tstore key for the token1 amount
     * @param _delta The `BeforeSwapDelta` that is being captured
     */
    function _captureDelta(
        SwapParams memory _params,
        bytes32 _key_amount0,
        bytes32 _key_amount1,
        BeforeSwapDelta _delta
    ) internal {
        (int token0, int token1) = _params.amountSpecified < 0 == _params.zeroForOne
            ? (-_delta.getSpecifiedDelta(), -_delta.getUnspecifiedDelta())
            : (-_delta.getUnspecifiedDelta(), -_delta.getSpecifiedDelta());

        // Store our amounts
        assembly {
            tstore(_key_amount0, token0)
            tstore(_key_amount1, token1)
        }
    }

    /**
     * Maps our swap fee to the expected event emit format.
     *
     * @param _params The `SwapParams` used to capture the delta
     * @param _key_fee0 The tstore key for the token0 fee amount
     * @param _key_fee1 The tstore key for the token1 fee amount
     * @param _delta The `uint` that is being captured for the fee
     */
    function _captureDeltaSwapFee(
        SwapParams memory _params,
        bytes32 _key_fee0,
        bytes32 _key_fee1,
        uint _delta
    ) internal {
        // The delta provided needs to be made negative
        int delta = -int(_delta);

        if (_params.amountSpecified < 0 == _params.zeroForOne) {
            assembly {
                tstore(_key_fee0, 0)
                tstore(_key_fee1, delta)
            }
        } else {
            assembly {
                tstore(_key_fee0, delta)
                tstore(_key_fee1, 0)
            }
        }
    }


    /**
     * Settles tokens against the PoolManager based on the BalanceDelta passed.
     *
     * @dev This is required to be separated due to Stack Too Deep errors
     *
     * @param _poolKey The pool key to settle against
     * @param _delta The BalanceDelta showing token amounts to settle
     */
    function _settleDelta(PoolKey memory _poolKey, BalanceDelta _delta) internal {
        if (_delta.amount0() < 0) {
            _poolKey.currency0.settle(poolManager, address(this), uint(-int(_delta.amount0())), false);
        } else if (_delta.amount0() > 0) {
            poolManager.take(_poolKey.currency0, address(this), uint(int(_delta.amount0())));
        }

        if (_delta.amount1() < 0) {
            _poolKey.currency1.settle(poolManager, address(this), uint(-int(_delta.amount1())), false);
        } else if (_delta.amount1() > 0) {
            poolManager.take(_poolKey.currency1, address(this), uint(int(_delta.amount1())));
        }
    }

    /**
     * This function should only be called by the `closeBidWall` function to unlock the {PoolManager}
     * interactions for the `{BidWall}.closeBidWall` function.
     *
     * @param _data The encoded {PoolKey} for the `closeBidWall` request
     *
     * @return result Empty data; nothing will be returned
     */
    function unlockCallback(
        bytes calldata _data
    ) internal returns (bytes memory result) {
        bidWall.closeBidWall(abi.decode(_data, (PoolKey)));
        return result;
    }

    /**
     * Resolves the real swapper. Routers obfuscate `_sender`, so pass `abi.encode(user)` in hookData.
     */
    function _resolveSwapper(
        address _sender,
        bytes calldata _hookData
    ) internal pure returns (address swapper_) {
        if (_hookData.length == 32) {
            swapper_ = abi.decode(_hookData, (address));
        } else if (_hookData.length == 20) {
            assembly {
                // load 32 bytes from calldata, shift right 12 bytes (96 bits)
                // to isolate the 20-byte address in the low bits
                swapper_ := shr(96, calldataload(_hookData.offset))
            }
        } else {
            swapper_ = _sender;
        }
    }

    /**
     * If the creator never purchased their premine, clear the tstore claim.
     * On FairLaunch deadline the tokens are burned with unsold FL supply; on sold-out the
     * tokens were already bought by the public so only the claim is cleared.
     */
    function _clearUnusedPremine(
        PoolId _poolId
    ) internal {
        int premine = _tload(PoolId.unwrap(_poolId));
        if (premine == 0) {
            return;
        }

        assembly {
            tstore(_poolId, 0)
        }
        emit PremineBurned(_poolId, uint(premine));
    }

    /**
     * Helper function to allow for tstore-d variables to be called individually. This saves us
     * defining an additional variable before our `tload` calls inside the function.
     *
     * @param _key The `tstore` key to load
     *
     * @return value_ The `int` value in the tstore
     */
    function _tload(bytes32 _key) internal view returns (int value_) {
        assembly { value_ := tload(_key) }
    }

    /**
     * Override to return true to make `_initializeOwner` prevent double-initialization.
     *
     * @return bool Set to `true` to prevent owner being reinitialized.
     */
    function _guardInitializeOwner() internal pure override returns (bool) {
        return true;
    }
}
